### ISSUE TITLE
road map

### ISSUE THREAD

**Issue by GopherJ** [casbin-rs/casbin-dashboard#1]
- [ ] client & server template
- [ ] building & packaging scripts including deb packaging
- [ ] authn via JWT
- [ ] user management, add, delete, update
- [ ] server side restful API
- [ ] server side structured logging setup
- [ ] client side basic authn, token persistence
- [ ] client side policy managment
- [ ] client side logging dashboard

**Comment by GopherJ** [comment]
Basic RESETful API design

1. **/api/v1/:domain//policies**
```
DELETE string[] | string[][]
POST string[] | string[][]
```

2. **/api/v1/:domain/roles**

```
POST
DELETE
```


3. **/api/v1/logging?start_timestamp= ?&end_timestamp = ? **

```
GET
```

....Todo

**Comment by GopherJ** [comment]
HOW to support other model as well? I have only RBAC experience but abac is also interesting.
